{% set version = "2019.1.0" %}

package:
  name: didsr-breast-phantom 
  version: {{ version }}

source:
  - git_url: https://github.com/DIDSR/breastPhantom
    git_rev: 370336f312074a8f90a37dfb51cee1a7e9bc517e
    folder: breastPhantom

build:
  number: 2
  skip: true  # [win or py2k]

outputs:
  - name: didsr-breast-phantom
    build:
      script: ${RECIPE_DIR}/build-bphantom.sh
      skip: true  # [win or py2k]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - boost-cpp
        - cmake >=3.9
        - zlib
        - liblapack
        - vtk
        - proj4
        - openmp
        - tbb-devel
      run:
        - {{ compiler('cxx') }}  # [linux]
        - boost-cpp
        - cmake >=3.9
        - zlib
        - liblapack
        - vtk
        - proj4
        - openmp
        - tbb-devel


about:
  home: https://breastphantom.readthedocs.io 
  license: CC0-1.0
  license_file: breastPhantom/COPYING.txt
  summary: 'DIDSR Anthropomorphic Breast Phantom Software'

  description: |
      DIDSR Anthropomorphic Breast Phantom Software
  doc_url: http://breastphantom.readthedocs.io/
  dev_url: https://github.com/DIDSR/breastPhantom 

extra:
  recipe-maintainers:
    - uvilla
